"""Add game_category to Response model and user_selectable_categories setting

Revision ID: 39ba7c67cc45
Revises: 645ea7ea27a3
Create Date: 2025-05-23 11:31:41.036513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ba7c67cc45'
down_revision = '645ea7ea27a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_category', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_responses_game_category'), ['game_category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_game_category'))
        batch_op.drop_column('game_category')

    # ### end Alembic commands ###
