"""Make Response.user_id non-nullable

Revision ID: 637dc589cec9
Revises: 7f82e9e986fe
Create Date: 2025-05-23 17:28:41.304452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637dc589cec9'
down_revision = '7f82e9e986fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
