"""Add points_awarded to Response model

Revision ID: 645ea7ea27a3
Revises: e7030ad0abcb
Create Date: 2025-04-13 16:24:35.226883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645ea7ea27a3'
down_revision = 'e7030ad0abcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_awarded', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_column('points_awarded')

    # ### end Alembic commands ###
