"""Add UserFeedback table

Revision ID: 97bdb0b79308
Revises: ebbe25d0592a
Create Date: 2025-05-25 15:40:33.232553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bdb0b79308'
down_revision = 'ebbe25d0592a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_address_at_submission', sa.String(length=120), nullable=True),
    sa.Column('nickname_at_submission', sa.String(length=80), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent_string', sa.String(length=255), nullable=True),
    sa.Column('page_context', sa.String(length=255), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_feedback_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedback_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_feedback_submitted_at'))

    op.drop_table('user_feedback')
    # ### end Alembic commands ###
