"""Add GameSummary table

Revision ID: ebbe25d0592a
Revises: 1cce687ff5fe
Create Date: 2025-05-25 06:46:34.527327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbe25d0592a'
down_revision = '1cce687ff5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_category', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('average_brier_score', sa.Float(), nullable=True),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_summaries_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_summaries_game_category'), ['game_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_summaries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_summaries_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_summaries_game_category'))
        batch_op.drop_index(batch_op.f('ix_game_summaries_completed_at'))

    op.drop_table('game_summaries')
    # ### end Alembic commands ###
